name: CI with Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-943f0c3
        id: prime-cache-943f0c3
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-943f0c3

      - name: Echo cache result
        run: echo "Cache hit = ${{ steps.prime-cache-943f0c3.outputs.cache-hit }}"

      - name: Create dummy files if cache miss
        if: steps.prime-cache-943f0c3.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/demo
          echo "Priming cache with demo file" > ~/.cache/demo/example.txt
